### Las pruebas de métodos http estarán aquí

### Actualizar el estado de una habitación

POST http://localhost:4000/api/room/0102 HTTP/1.1
Content-Type: application/json

{
    "estado": "ocupada"
}

### Obtener todas las habitaciones

GET http://localhost:4000/api/room/ HTTP/1.1

### Obtener habitación por número de habitación

GET http://localhost:4000/api/room?number=0101 HTTP/1.1

### Obtener habitación por tipo de habitación

GET http://localhost:4000/api/room?type=Matrimonial HTTP/1.1


### Obtener habitación por estado

GET http://localhost:4000/api/room?status=ocupada HTTP/1.1


### Crear una reserva completa

POST http://localhost:4000/api/reservation HTTP/1.1
Content-Type: application/json

{
    "tipoServicio": "basico",
    "fechaInicio": "2020-12-15",
    "fechaFin": "2020-12-20",
    "mailPago": "example@example.com",
    "telefonoPago": "999999999",
    "habitaciones": [
        {
            "numero": "0201"
        },
        {
            "numero": "0202"
        },
        {
            "numero": "0103"
        }
    ],
    "huespedes": [
        {
            "nombre": "Juan",
            "apellido": "Perez",
            "dni": "12345678",
            "telefono": "999999999",
            "mail": "a@gmail.com"
        },
        {
            "nombre": "Juan",
            "apellido": "Perez",
            "dni": "23409823",
            "telefono": "999999999",
            "mail": "b@gmail.com"
        },
        {
            "nombre": "Juan",
            "apellido": "Perez",
            "dni": "12309834",
            "telefono": "999999999",
            "mail": "c@gmail.com"
        }
    ]
}

### PAYMENT

POST http://localhost:4000/api/payment/create-order HTTP/1.1
Content-Type: application/json

{
  "currentUrl": "http://localhost:3000",
  "mailPago": "jmondalgotapia@gmail.com",
  "telefonoPago": "953923333",
  "tipoServicio": "basico",
  "fechaInicio": "2024-04-02",
  "fechaFin": "2024-04-06",
  "habitaciones": [
    { "numero": "0301" },
    { "numero": "0302" },
    { "numero": "0303" },
    { "numero": "0103" }
  ],
  "huespedes": [
    {
      "nombre": "Jesus Emanuel",
      "apellido": "Mitma Vera",
      "dni": "12312312",
      "telefono": "123123123",
      "mail": "qweqwe@qweqew.qwe"
    }
  ]
}

### Users

### Create
POST http://localhost:4000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "rol": "recepcionista",
    "nombres": "Jhon",
    "apellidos": "Doe",
    "dni": "12345678",
    "telefono": "999999999",
    "mail": "jmondalgotapia@gmail.com",
    "password": "recep123",
    "url_imagen": "https://www.github.com/Jmond544.png"
}

### another user

POST http://localhost:4000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "rol": "recepcionista",
    "nombres": "Jorge",
    "apellidos": "Sanchez",
    "dni": "87654321",
    "telefono": "999999999",
    "mail": "jorgeesanchez97@gmail.com",
    "password": "recep123",
    "url_imagen": "https://www.github.com/Torvalds.png"
}

### Login

POST http://localhost:4000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "mail": "jmondalgotapia@gmail.com",
    "password": "recep123"
}

### Verify code

POST http://localhost:4000/api/user/verify HTTP/1.1
Content-Type: application/json

{
    "mail": "jmondalgotapia@gmail.com",
    "codigo": "EWE2KT",
    "password": "recep123"
}

### Get user by access token

GET http://localhost:4000/api/user/profile/ HTTP/1.1
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNjdhZTliLWQ0MTQtMTFlZS04ODA3LThjMTY0NTAxOTZmOSIsImlhdCI6MTcwODg4OTUzMiwiZXhwIjoxNzA4OTc1OTMyfQ.8RDzBdCaIOrtkYdjfCrHlWAvn7nB_gPmwVcYbA6btK4

### Query reservations

GET http://localhost:4000/api/reservation/query?tipoFiltro=numeroHabitacion&valor=0103&fechaInicio=2020-10-01&fechaFin=2021-10-10 HTTP/1.1

### Query all reservations

GET http://localhost:4000/api/reservation/query?tipoFiltro=numeroHabitacion&valor=all&fechaInicio=2020-10-01&fechaFin=2021-10-10 HTTP/1.1


### Query phone number

GET http://localhost:4000/api/reservation/query?tipoFiltro=telefonoReserva&valor=999999999&fechaInicio=2020-10-01&fechaFin=2021-10-10 HTTP/1.1