### Las pruebas de métodos http estarán aquí

### Actualizar el estado de una habitación

POST http://localhost:4000/api/room/0102 HTTP/1.1
Content-Type: application/json

{
    "estado": "ocupada"
}

### Obtener todas las habitaciones

GET http://localhost:4000/api/room/ HTTP/1.1

### Obtener habitación por número de habitación

GET http://localhost:4000/api/room?number=0101 HTTP/1.1

### Obtener habitación por tipo de habitación

GET http://localhost:4000/api/room?type=Matrimonial HTTP/1.1


### Obtener habitación por estado

GET http://localhost:4000/api/room?status=ocupada HTTP/1.1


### Crear una reserva completa

POST http://localhost:4000/api/reservation HTTP/1.1
Content-Type: application/json

{
    "tipoServicio": "basico",
    "fechaInicio": "2020-12-15",
    "fechaFin": "2020-12-20",
    "mailPago": "example@example.com",
    "telefonoPago": "999999999",
    "habitaciones": [
        {
            "numero": "0201"
        },
        {
            "numero": "0202"
        },
        {
            "numero": "0103"
        }
    ],
    "huespedes": [
        {
            "nombre": "Juan",
            "apellido": "Perez",
            "dni": "12345678",
            "telefono": "999999999",
            "mail": "a@gmail.com"
        },
        {
            "nombre": "Juan",
            "apellido": "Perez",
            "dni": "23409823",
            "telefono": "999999999",
            "mail": "b@gmail.com"
        },
        {
            "nombre": "Juan",
            "apellido": "Perez",
            "dni": "12309834",
            "telefono": "999999999",
            "mail": "c@gmail.com"
        }
    ]
}

### PAYMENT

POST http://localhost:4000/api/payment/create-order HTTP/1.1
Content-Type: application/json

{
  "mailPago": "jmondalgotapia@gmail.com",
  "telefonoPago": "953923333",
  "tipoServicio": "basico",
  "fechaInicio": "2024-04-02",
  "fechaFin": "2024-04-06",
  "habitaciones": [
    { "numero": "0301" },
    { "numero": "0302" },
    { "numero": "0303" },
    { "numero": "0103" }
  ],
  "huespedes": [
    {
      "nombre": "Jesus Emanuel",
      "apellido": "Mitma Vera",
      "dni": "12312312",
      "telefono": "123123123",
      "mail": "qweqwe@qweqew.qwe"
    }
  ]
}
